name: flutter_engine_cli
description: A powerful CLI to bootstrap and manage scalable, feature-first Flutter projects.
version: 1.0.2
repository: https://github.com/KunalTayal/flutter_engine_cli

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  tint: ^2.0.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

executables:
  flutter_engine_cli: